tinymce.addI18n('tooltips',{
"Undo": "Undo (Ctrl+Z)",
"Redo": "Redo (Ctrl+Y or Ctrl+Shift+Z)",
"Cut": "Cut (Ctrl+X)",
"Copy": "Copy (Ctrl+C)",
"Paste": "Paste (Ctrl+V)",
"Select all": "Select all (Ctrl+A)",
"Bold": "Bold (Ctrl+B)",
"Italic": "Italic (Ctrl+I)",
"Underline": "Underline (Ctrl+U)",
"Strikethrough": "Strikethrough (Alt+Shift+5)",
"Superscript": "Superscript (Ctrl+.)",
"Subscript": "Subscript (Ctrl+,)",
"Clear formatting": "Clear formatting (Ctrl+\\)",
"Bullet list": "Bullet list (Ctrl+Shift+8)",
"Numbered list": "Numbered list (Ctrl+Shift+7)",
"Insert/edit link": "Insert/edit link (Ctrl+K)",
"Blockquote": "Blockquote (Ctrl+])",
"Paste as text": "Paste as text (Shift+Ctrl+V)",
"Insert link": "Insert link (Ctrl+K)",
"Find and replace": "Find and replace (Ctrl+F or Ctrl+H)",
"Source Code": "HTML code",
});

